### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by kendall** [antoniogarrote/stardog-rb#1]
Antonio,

This looks good so far. Have you decided which license you will make this available under?

**Comment by antoniogarrote** [comment]
Not really. 

Do you have any preference?

**Comment by kendall** [comment]
Well, it's yr code, so it's up to you. If it's Apache 2, then we might be able to help extend it, etc.

But I'm not in the habit of telling people how they should make their property available for my use; i.e., use any license yr comfortable with, but if there's no license at all, the uncertainty may tend to prevent people from contributing. ;>

**Comment by antoniogarrote** [comment]
That's exactly what I meant. I wasn't sure what open source license would be more friendly for the people using Stardog.

Not it is licensed under the Apache 2.0 License.

Cheers.
